name: Build and Test

on: [push, pull_request]

jobs:

  test-windows-x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: dotnet workload install android ios maccatalyst
    - run: dotnet --info
    - name: Test (.NET 6.0/Debug)
      run: dotnet test -f net6.0 -c Debug
    - name: Test (.NET 6.0/Release)
      run: dotnet test -f net6.0 -c Release
    - name: Pack
      run: dotnet pack -c Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: '**/*.nupkg'

  test-ubuntu-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: dotnet workload install android
    - run: dotnet --info
    - name: Test (.NET 6.0/Debug)
      run: dotnet test -f net6.0 -c Debug
    - name: Test (.NET 6.0/Release)
      run: dotnet test -f net6.0 -c Release

  test-alpine-x64:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    steps:
    - uses: actions/checkout@v3
    - run: dotnet workload install android
    - run: dotnet --info
    - name: Test (.NET 6.0/Debug)
      run: dotnet test -f net6.0 -c Debug
    - name: Test (.NET 6.0/Release)
      run: dotnet test -f net6.0 -c Release

  test-macos-x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: dotnet workload install android ios maccatalyst
    - run: dotnet --info
    - name: Test (.NET 6.0/Debug)
      run: dotnet test -f net6.0 -c Debug
    - name: Test (.NET 6.0/Release)
      run: dotnet test -f net6.0 -c Release
    - name: Test (.NET 6.0 Mac Catalyst/Debug)
      run: dotnet test -f net6.0-maccatalyst -c Debug
    - name: Test (.NET 6.0 Mac Catalyst/Release)
      run: dotnet test -f net6.0-maccatalyst -c Release
